CareMarketplaceApp/urls.py
from django.urls import path
from . import views
from .views_all import accountsView, careGiverView, careHomeView

urlpatterns = [
    # path('WelcomePage', views.WelcomePage, name='Welcomepage'),
    path('', views.index, name='index'), 
    path('registerCareGiver', accountsView.registerCareGiver, name='registerCareGiver'), 
    path('registerCareHome', accountsView.registerCareHome, name='registerCareHome'), 
    path('login', accountsView.loginAccount, name='login'),
    path('logout', accountsView.logoutAccount, name='logout'),
    path('marketplace', accountsView.marketplace, name='marketplace'),
    path('careGiverDashboard', careGiverView.careGiverDashboard, name='careGiverDashboard'), 
    path('careGiverBioData', careGiverView.careGiverBiodata, name='careGiverBioData'),
    path('careGiverEducation', careGiverView.careGiverEducation, name='careGiverEducation'),
    path('careGiverWorkType', careGiverView.careGiverWorkType, name='careGiverWorkType'),
    path('careHomeDashboard', careHomeView.careHomeDashboard, name='careHomeDashboard'), 
    path('careHomeProfile', careHomeView.careHomeProfile, name='careHomeProfile'), 
    path('careHomeSearch', careHomeView.careHomeSearch, name='careHomeSearch'), 
    path('bookCareGiver/<int:user_id>/', careHomeView.bookCareGiver, name='bookCareGiver'),
    path('bookCareGiver', careHomeView.bookCareGiver, name='bookCareGiver'),
    path('careGiverDetails/<int:user_id>/', careHomeView.careGiverDetails, name='bookCareGiver')
    
    
]

CareMarketplaceSystem/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CareMarketplaceApp.urls'))

]

CareMarketplaceApp/forms/CareHomeForm.py
from django import forms
from ..models.CareGiverModels import CareGiverBioDataProfile, CareGiverEducationProfile, CareGiverWorkExperienceProfile
from ..models.CareHomeModels import CareHomeProfile

class CareHomeProfileForm(forms.ModelForm):
     def __init__(self, *args, **kwargs):
        super(CareHomeProfileForm, self).__init__(*args, **kwargs)
        # Add custom CSS class to each form field
        self.fields['address'].widget.attrs['readonly'] = True
        self.fields['state'].widget.attrs['readonly'] = True
        self.fields['country'].widget.attrs['readonly'] = True
        self.fields['city'].widget.attrs['readonly'] = True

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'mdc-text-field__input'
            

     class Meta:
        model = CareHomeProfile
        fields = '__all__'
        exclude = ['userAuth', 'userType', 'postCodeAddress', 'postCodeLongitude', 'postCodeLatitude', 'isActive', 'dateCreated', 'modfiedBy']

class CareHomeSearchForm(forms.Form): 
   CARE_CHOICES =[
            ('Elderly_care', 'Elderly Care'),
            ('Residential_care', 'Residential Care'),
            ('Respite_care', 'Respite Care'),
            ('Dementia_care', 'Dementia Care'),
            ('Domiciliary_care', 'Domiciliary Care'),
            ('Assisted_living', 'Assisted Living'),
            ('Disability_care', 'Disability Care'),
            ('Nursing_care', 'Nursing Care'),
            ('Mental_health', 'Mental Health Cares'),
         ]

   availability = [
      ('fullTime', 'Full Time'),
      ('partTime', 'Part Time')
   ]

   radius = [
      ('1', '0 - 1 miles'),
      ('2', '1 to 2 miles'),
      ('3', '2 to 3 miles'),
      ('4', '3 to 4 miles'),
      ('5', '4 to 5 miles'),
      ('6', '5 and above')

   ]

   care_options = forms.MultipleChoiceField(
         choices=CARE_CHOICES,
         widget=forms.CheckboxSelectMultiple,
         required=False
      )
   availability = forms.ChoiceField(
         choices=availability,
         widget=forms.RadioSelect,
         required=False
      )
   radius_search = forms.ChoiceField(
         choices=radius,
         widget=forms.RadioSelect,
         required=False
      )

 

templates/ALogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>CARE MARKETPLACE SYSTEM</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png'" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png'" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Medilab
  * Template URL: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/
  * Updated: Mar 17 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex justify-content-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope"></i> <a href="mailto:contact@example.com">jefkins@dmu.edu.uk</a>
        <i class="bi bi-phone"></i> +1 000000
      </div>
      <div class="d-none d-lg-flex social-links align-items-center">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div>
    </div>
  </div>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="index.html">Care Marketplace System</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">Register</a></li>
          <li><a class="nav-link scrollto" href="#services">Login</a></li>
          
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <a href="#appointment" class="appointment-btn scrollto"><span class="d-none d-md-inline">Find a</span> Caregiver</a>

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container">
      <h1>Welcome to Care Marketplace System</h1>
      <h2>An MSc Dissertation project by Jefkins Nwabenu</h2>
      <a href="#about" class="btn-get-started scrollto">Register as a CareHome</a> |  <a href="#about" class="btn-get-started scrollto">Register as a Care Giver</a>
    </div>
  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= Why Us Section ======= -->
    <!-- <section id="why-us" class="why-us">
      <div class="container">

        <div class="row">
          <div class="col-lg-4 d-flex align-items-stretch">
            <div class="content">
              <h3>Why Choose Medilab?</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit
                Asperiores dolores sed et. Tenetur quia eos. Autem tempore quibusdam vel necessitatibus optio ad corporis.
              </p>
              <div class="text-center">
                <a href="#" class="more-btn">Learn More <i class="bx bx-chevron-right"></i></a>
              </div>
            </div>
          </div>
          <div class="col-lg-8 d-flex align-items-stretch">
            <div class="icon-boxes d-flex flex-column justify-content-center">
              <div class="row">
                <div class="col-xl-4 d-flex align-items-stretch">
                  <div class="icon-box mt-4 mt-xl-0">
                    <i class="bx bx-receipt"></i>
                    <h4>Corporis voluptates sit</h4>
                    <p>Consequuntur sunt aut quasi enim aliquam quae harum pariatur laboris nisi ut aliquip</p>
                  </div>
                </div>
                <div class="col-xl-4 d-flex align-items-stretch">
                  <div class="icon-box mt-4 mt-xl-0">
                    <i class="bx bx-cube-alt"></i>
                    <h4>Ullamco laboris ladore pan</h4>
                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt</p>
                  </div>
                </div>
                <div class="col-xl-4 d-flex align-items-stretch">
                  <div class="icon-box mt-4 mt-xl-0">
                    <i class="bx bx-images"></i>
                    <h4>Labore consequatur</h4>
                    <p>Aut suscipit aut cum nemo deleniti aut omnis. Doloribus ut maiores omnis facere</p>
                  </div>
                </div>
              </div>
            </div><!-- End .content
          </div>
        </div>

      </div>
    </section>
     -->
    

   
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Care Marketplace System</h3>
            <p>
              An MSc Dissertation project carried out by Jefkins Nwabenu<br><br>
              
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
              <li><a class="nav-link scrollto" href="#about">Register</a></li>
              <li><a class="nav-link scrollto" href="#services">Login</a></li>
            </ul>
          </div>

          

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Care Marketplace System 2024</span></strong>. All Rights Reserved
        </div>
      
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/AccountsTemplate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block PageTitle %}
  {% endblock %}
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'dashboardassets/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'dashboardassets/vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- Layout styles -->
  <link rel="stylesheet" href="{% static 'dashboardassets/css/demo/style.css' %}">
  <!-- End layout styles -->
  <link rel="shortcut icon" href="{% static 'dashboardassets/images/favicon.png' %}" />
</head>
<body>
  <script src="{% static 'dashboardassets/js/preloader.js' %}"></script>
  <div class="body-wrapper">
    <div class="main-wrapper">
      <div class="page-wrapper full-page-wrapper d-flex align-items-center justify-content-center">
        <main class="auth-page">
          <div class="mdc-layout-grid">
            <div class="mdc-layout-grid__inner">
              <div class="stretch-card mdc-layout-grid__cell--span-4-desktop mdc-layout-grid__cell--span-1-tablet"></div>
              <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-4-desktop mdc-layout-grid__cell--span-6-tablet">
              {% block PageContent %}
              {% endblock %}
              
              
                <!-- <div class="mdc-card">
                  <form action="register" method="post" role="form">
                    {% csrf_token %}
                 
                    <div class="mdc-layout-grid">
                  
        {% for message in messages %}
        <p>{{message}}</p>
        {% endfor %}
                      <div class="mdc-layout-grid__inner">
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                            <input name="firstName" class="mdc-text-field__input" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">First Name</label>
                          </div>
                        </div>
                     
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                            <input name="lastName" class="mdc-text-field__input" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Last Name</label>
                          </div>
                        </div>
                      
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                            <input name="username" class="mdc-text-field__input" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Username</label>
                          </div>
                        </div>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                            <input name="Email" class="mdc-text-field__input" type="email" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Email</label>
                          </div>
                        </div>
                      
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                            <input name="password" class="mdc-text-field__input" type="password" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Choose Password</label>
                          </div>
                        </div>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                            <input name="confirmPassword" class="mdc-text-field__input" type="password" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Confirm Password</label>
                          </div>
                        </div>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                            <input name="phoneNumber" class="mdc-text-field__input" type="text" id="text-field-hero-input">
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Phone Number</label>
                          </div>
                        </div>
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                          <div class="mdc-text-field w-100">
                             <select name="accountType" class="mdc-text-field__input" id="text-field-hero-input">
                              <option value="">--Select--</option>
                              <option value="CareGiver">Care Giver</option>
                              <option value="CareHome">Care Home</option>
                            </select>
                            <div class="mdc-line-ripple"></div>
                            <label for="text-field-hero-input" class="mdc-floating-label">Account Type</label>
                          </div>
                        </div>
                      
                      
                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                         
                          <input type="submit" class="mdc-button mdc-button--raised w-100" value="Register">
                          
                        </div>

                        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                         
                          <p>Already Have an Account? <a href="login" class="mdc-button mdc-button--raised w-100">Login Here</a></p>
                            
                        </div>
                      </div>
                    </div>
                  </form>
                </div> -->
              </div>
              <div class="stretch-card mdc-layout-grid__cell--span-4-desktop mdc-layout-grid__cell--span-1-tablet"></div>
            </div>
          </div>
        </main>
      </div>
    </div>
  </div>
   <!-- plugins:js -->
   <script src="{% static 'dashboardassets/vendors/js/vendor.bundle.base.js' %}"></script>
   <!-- endinject -->
   <!-- Plugin js for this page-->
   <!-- End plugin js for this page-->
   <!-- inject:js -->
   <script src="{% static 'dashboardassets/js/material.js' %}"></script>
   <script src="{% static 'dashboardassets/js/misc.js' %}"></script>
   <!-- endinject -->
   <!-- Custom js for this page-->
   <!-- End custom js for this page-->
</body>
</html>

templates/careHomeSearch.html
{% extends 'CareHomeDashboardTemplate.html' %}

{% block Header %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Map</title>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<!-- Leaflet CSS -->
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />

<!-- Leaflet JavaScript -->
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>


<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    /* Custom CSS */
    .card {
      margin-bottom: 20px;
    }
    #map {
        height: 400px;
    }
 
    .progress-bar {
        width: 100%;
        height: 20px;
        background-color: #f2f2f2;
        border-radius: 10px;
        margin-bottom: 10px;
    }
    .progress-bar-inner {
        height: 100%;
        border-radius: 10px;
        background-color: #007bff;
    }
</style>
{% endblock %}






{% block PageContent %}
 


<script>
    $(document).ready(function() {
        // Initialize the progress bar with the default value
        updateProgressBar($("#radius-slider").val());

        // Attach event listener to the range slider
        $("#radius-slider").on("input", function() {
            var value = $(this).val();
            console.log(value)
            updateProgressBar(value);
        });

        // Function to update the progress bar width
        function updateProgressBar(value) {
            var progressBar = $("#progress-bar");
            progressBar.css("width", value + "%");
        }
    });
</script>

 


<!-- <main class="content-wrapper">

    <div id="map"></div>

<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script>
var map = L.map('map').setView([51.505, -0.09], 13);  // Initialize map with default center and zoom level

// Add tile layer (optional)
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
}).addTo(map);

// Add markers for each manually created location
var locations = {{ locations|safe }};  // Pass locations from Django view
locations.forEach(function(location) {
    var marker = L.marker([location.latitude, location.longitude]).addTo(map);
    // Add popup (optional)
    marker.bindPopup(location.name);
});
</script>
  
 
</main>

<main class="content-wrapper">
  <div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
      <div class="mdc-layout-grid__cell--span-12">
        <div class="mdc-card">
          {% if user.is_authenticated %}

          <h6>Welcome {{user.username}} to your Care Home Dashboard</h4>

            {% endif %}

        </div>
 -->





 <main class="content-wrapper">
  <div class="mdc-layout-grid">
    

 <div class="card">
  <h5 class="card-header">Find Care Givers</h5>
  <div class="card-body">
    <p class="card-title">Select the filter options to find suitable Caregivers</p>
    <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
     -->

   
     {% if form.errors %}
     <div class="alert alert-danger">
         <strong>Error!</strong> Please correct the following errors:
         <ul>
             {% for field, errors in form.errors.items %}
                 {% for error in errors %}
                     <li>{{ error }}</li>
                 {% endfor %}
             {% endfor %}
         </ul>
     </div>
 {% endif %}
  <form method="post" action="careHomeSearch" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-12">
        <p class="card-text"> <strong>Select Care Experience </strong></p>
          <!-- <label for="id_care_options">Select Care Options:</label> -->
          {% for option in form.care_options %}
   
    {{ option.tag }}  {{ option.choice_label }} &nbsp;&nbsp;&nbsp;
  
    {%endfor%} 
       
          <!-- {{ form.care_options }} -->
      </div>
      <div class="form-group col-md-12">
        <!-- <label for="id_radius_search">Select Radius Search:</label> -->
        <p class="card-text"> <strong>Select Location range </strong> </p>
        <div class="progress-bar">
          <div class="progress-bar-inner" id="progress-bar"></div>
      </div>
      
      <input type="range" min="0" max="100" value="50" class="slider" id="radius-slider">
      
        {% for option in form.radius_search %}
        
          {{ option.tag }}  {{ option.choice_label }} &nbsp;&nbsp;&nbsp;
    
          {%endfor%} 
        <!-- {{ form.radius_search }} -->
    </div>
      <div class="form-group col-md-6">
        <p class="card-text"> <strong>Select Availability </strong></p>
          <!-- <label for="id_availability">Select Availability:</label> -->
          
          {% for option in form.availability %}
          
            {{ option.tag }}  {{ option.choice_label }} &nbsp;&nbsp;&nbsp;
         
            {%endfor%} 
          <!-- {{ form.availability }} -->
      </div>
      
    </div>

    <button class="mdc-button mdc-button--raised" type="submit">Search Care Givers</button>
  
</form>
  </div>

  <!-- <a href="#" class="btn btn-primary">Go back to Dashboard</a> -->
</div>
 
 

<div class="row">
  {% if careGivers is None %}
  <div class="card">
  <p class="text-danger">No Care Givers found!</p>
</div>
  {% endif %}
  {% for caregiver in careGivers %}  
<div class="card col-lg-3">
  <img src="../Media_Files/image.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{caregiver.first_name}} {{caregiver.last_name}}</h5>
     <p>Care Experience: </p>
     <p>Distance away: </p>
  </div>
   
  <div class="card-body">
    <a href="careGiverDetails/{{caregiver.userAuth_id}}" class="btn btn-primary">View Profile</a>
    <a href="bookCareGiver/{{caregiver.userAuth_id}}" class="btn btn-primary">Book Caregiver</a>
    
  </div>
</div>
{% endfor %}

</div>
 <div>

  <div id="map" style="height: 400px;"></div>

<script>
    var map = L.map('map').setView([51.505, -0.09], 13);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    // Loop through locations and add markers to the map
    {% for location in locations %}
    L.marker([{{ location.latitude }}, {{ location.longitude }}]).addTo(map)
        .bindPopup("{{ location.name }}");
    {% endfor %}
</script>



 </div>  

    
  </div>
 </main>

 
<!-- 

 {% for caregiver in careGivers %}
 <div class="mdc-layout-grid">
  <h4>List of Care Givers</h4>
 <div class="mdc-layout-grid__inner">
  <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-4-desktop mdc-layout-grid__cell--span-4-tablet">
    <div class="mdc-card info-card info-card--success">
      <div class="card-inner">
        <h5 class="card-title">Name: {{caregiver.first_name}}</h5>
        <h5 class="font-weight-light pb-2 mb-1 border-bottom">Email: {{caregiver.email}}</h5>
        <h5 class="font-weight-light pb-2 mb-1 border-bottom">Phone: {{caregiver.primary_phone_number}}</h5>
        <h5 class="font-weight-light pb-2 mb-1 border-bottom">Address: {{caregiver.postCodeAddress}}</h5>
        <hr>
        <h5 class="font-weight-light pb-2 mb-1 border-bottom">Care Experience: </h5>
        
        <p class="tx-12 text-muted">Availability: {{caregiver.email}}</p>
         <button>Contact</button>
      </div>
    </div>
  </div>
 </div>
 </div>
 {% endfor %} -->

        
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      
 
         

        




     
      </div>
    </div>
  </div>
  </div>
</main> 
{% endblock %}


<!-- map.html -->